### ISSUE TITLE
plugin not yet compatible with version 9.3 of GLPI

### ISSUE THREAD

**Issue by joaovitorcavalcante** [pluginsGLPI/satisfaction#10]
I installed GLPI in its newest version, but the satisfaction plugin is not yet available for installation.

What is the risk of removing the line `version_compare (GLPI_VERSION, '9.3', 'ge') from the` plugin_satisfaction_check_prerequisites` method?

Thanks in advance for your time.

**Comment by amma35** [comment]
There will be many PHP errors and some features that may not work.

**Comment by amma35** [comment]
fix https://github.com/pluginsGLPI/satisfaction/releases/tag/1.3.0

**Comment by joaovitorcavalcante** [comment]
Thank you so much
