### ISSUE TITLE
Tags don't work 

### ISSUE THREAD

**Issue by iamme007** [pluginsGLPI/satisfaction#12]
Hello,

I would like to know if it is possible to have the answers & question integrared in the mail (notifications) of the satisfaction survey. Because, the tags ##satisfaction. question## & ##satisfaction. answer## does not work 
Thank you for your help.

**Comment by amma35** [comment]
You have well like this without space: ##satisfaction.question### & ##satisfaction.answer##

**Comment by iamme007** [comment]
i've tried without space but it doesn't work :/
