### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by juliosw** [pluginsGLPI/satisfaction#24]
Glpi Version 9.5.0
Satisfaction 1.7.0
Debian 10 Buster
nginx 1.14.2

Sintoms:

## when I try to save a reminder
![image](https://user-images.githubusercontent.com/45014255/95497005-0a644100-0978-11eb-94cc-0c92fdb6cfc6.png)
![image](https://user-images.githubusercontent.com/45014255/95497037-1819c680-0978-11eb-9a2a-09c2d8965330.png)

## when I try to add a translation, nothing happens
![image](https://user-images.githubusercontent.com/45014255/95497184-4e574600-0978-11eb-980a-5692d935e3ae.png)

at the time of installing the plugin the tables were not created. I installed the tables manually.

Can you help me?

**Comment by gguib** [comment]
Hi,

I fix Save reminder problem on post. However, i retry install & update and it works well, adding a translation as well.
Have you got somme sql or php logs when you post translation, on install ?

**Comment by tsmr** [comment]
Old issue. I close
