### ISSUE TITLE
Fatal Error while installing the plugin GLPI 9.1.6

### ISSUE THREAD

**Issue by roshanroche** [pluginsGLPI/satisfaction#3]
Dear @amma35 ,
i am getting this following error while installing the plugin
Fatal error: Uncaught Zend\I18n\Exception\ParseException: Unknown or invalid parser rule: nplurals=INTEGER; plural=EXPRESSION; in /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php:194 Stack trace: #0 /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php(149): Zend\I18n\Translator\Plural\Rule::fromString(' nplurals=INTEG...') #1 /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Translator.php(700): Zend\I18n\Translator\Loader\Gettext->load('en_GB', '/var/www/html/g...') #2 /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Translator.php(572): Zend\I18n\Translator\Translator->loadMessagesFromFiles('satisfaction', 'en_GB') #3 /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Translator.php(440): Zend\I18n\Translator\Translator->loadMessages('satisfaction', 'en_GB') #4 /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Translator.php(354): Zend\I18n\Translator\Translator->getTr in /var/www/html/glpi9.1.6/vendor/zendframework/zend-i18n/src/Translator/Plural/Rule.php on line 194

**Comment by amma35** [comment]
Yes, it's a language file problem.
You must replace the files in_GB.po and in_GB.mo, see https://github.com/pluginsGLPI/satisfaction/commit/bcf17272a839cb26293e0e40cda1701ca304151e

**Comment by amma35** [comment]
see release https://github.com/pluginsGLPI/satisfaction/releases/tag/1.1.1

**Comment by roshanroche** [comment]
Thanks @amma35  its working fine now
