### ISSUE TITLE
GLPI 9.5.6 Satisfaction 1.5.2 - can't add translation

### ISSUE THREAD

**Issue by DockCZ** [pluginsGLPI/satisfaction#31]
Hello,
I have a problem with translations. I am not able to add the translation.

GLPI: 9.5.6
satisfaction: 1.5.2

When add translation I am redirected to /plugins/satisfaction/ajax/surveytranslation.form.php and get response "The action you have requested is not allowed.".

The installation procceded without problems.
I am able to create survey.
I use user with all rights for Satisfaction survey.

**Comment by Yfavre73** [comment]
Hello,
I have the same problem but i'm using GLPI 10.

**Comment by tsmr** [comment]
Fixed in last version for GLPI 10
