### ISSUE TITLE
Plugin - Mais Relatórios

### ISSUE THREAD

**Issue by ppsnetto** [pluginsGLPI/satisfaction#33]
Prezados, Boa tarde !

Meu nome é Pedro, recentemente atualizamos o GLPI de onde trabalho(Prefeitura Municipal de Santa Luzia-MG) para o 10.0.2. Identifique dois problemas, 

Tipos de Chamados:

- Quando habilitado para exigir um documento é anexo, ocorre problema na abertura de chamado, o anexo entra em Loop, exigindo que seja anexado documentos, mesmo após o mesmo estar anexado.
- Plugins, utilizamos muito o "Mais Relatórios", porém o mesmo não está disponível para download para a versão 10.0.2

**Comment by tsmr** [comment]
Sorry but write in english. And your problems are not linked with this plugin. I close
