### ISSUE TITLE
how to view full survey results ?

### ISSUE THREAD

**Issue by AtoWeb** [pluginsGLPI/satisfaction#43]
Hello

I use the More Satisfaction plugin to add 5 questions to the satisfaction form. It works well. 👍 

- In /plugins/satisfaction/front/survey.php I see these responses, but without the comments field.
-In the ticket list (/front/ticket.php) I can display the overall rating and the comment field but not the additional questions.

How can we see all the survey responses in one place?

**Comment by tsmr** [comment]
On /marketplace/satisfaction/front/survey.form.php?id=X - into the Result tab
