### ISSUE TITLE
 Create a pop-up search every time the called to quit.

### ISSUE THREAD

**Issue by mrcssilvasouza** [pluginsGLPI/satisfaction#8]
It would be very interesting if they created a popup. Every time the call is solved, open a pop-up with satisfaction search. Every time the user accesses the GLPI, and if there are pending searches, open a popup as well. It would greatly help users to respond to the survey. The way it works today is not efficient.

**Comment by amma35** [comment]
The plugin only adds questions to the existing one in GLPI. This would be a suggestion to GLPI.
